### ISSUE TITLE
Needs a release

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel-xlsbr#2]
Unreleased..

**Comment by chfw** [comment]
one primitive release is done.

**Comment by jayvdb** [comment]
Packaged

1. https://build.opensuse.org/package/show/home:jayvdb:pyexcel/python-pyxlsb
2. https://build.opensuse.org/package/show/home:jayvdb:pyexcel/python-pyexcel-xlsbr

Main problem is `tests/__init__.py` is missing, so py27 tests fail.
